logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

server:
  port: 8088
spring:
  rabbitmq:
    host: 192.168.11.10 # 你的虚拟机IP
    port: 5672 # 端口
    virtual-host: /hmall # 虚拟主机
    username: hmall # 用户名
    password: 123 # 密码
    listener:
      simple:
        prefetch: 1 # 每次只能获取一条消息，处理完成才能获取下一个消息
        acknowledge-mode: auto # none关闭 auto自动确认 manual手动确认
        retry:
          enabled: true # 开启消费者失败重试
          initial-interval: 1000ms # 初始的失败等待时间为1秒
          multiplier: 1 # 下次失败的等待时长倍数，下次等待时长 = multiplier * last-interval
          max-attempts: 3 # 最大失败重试次数
          stateless: true # true 无状态 false 状态


